CREATE TABLE IF NOT EXISTS Perk (
                      perk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR NOT NULL,
                      price DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS Apartment (
                           apartment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           capacity INT NOT NULL,
                           price DOUBLE PRECISION,
                           status VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS Client (
                        client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR NOT NULL,
                        checkin TIMESTAMP,
                        checkout TIMESTAMP,
                        apartment_id BIGINT,
                        status VARCHAR NOT NULL,
                        staycost DOUBLE PRECISION,
                        quantityofpeople INT,
                        FOREIGN KEY (apartment_id) REFERENCES Apartment(apartment_id)
);

CREATE TABLE IF NOT EXISTS Client_Perk (
                             client_id BIGINT,
                             perk_id BIGINT,
                             PRIMARY KEY(client_id, perk_id),
                             FOREIGN KEY (client_id) REFERENCES Client(client_id),
                             FOREIGN KEY (perk_id) REFERENCES Perk(perk_id)
);