version: '3'

services:
  postgres:
    image: 'postgres:15-bullseye'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=db_hotel_Andersen'

  app:
    build: ./
    container_name: 'java-app'
    ports:
    - 8080:8080